/** Export every authored file and lockfile in a single reviewable Markdown artifact; never include secrets or local data. */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
const excluded = new Set([
  "node_modules",
  ".git",
  ".local",
  "dist",
  "coverage",
  "test-results",
  "playwright-report",
  ".pnpm-store",
  ".generated",
  ".agents",
  ".codex",
]);
function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (excluded.has(entry.name)) return [];
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return walk(path);
    if (
      entry.name === "SOURCEBOOK.md" ||
      entry.name.endsWith(".log") ||
      (entry.name.startsWith(".env") && entry.name !== ".env.example")
    )
      return [];
    return [relative(".", path).replaceAll("\\", "/")];
  });
}
const priority = [
  "README.md",
  "docs/SETUP.md",
  "scripts/doctor.ts",
  "scripts/bootstrap-repo.ps1",
  "docs/DECISIONS.md",
  "docs/GAME_DESIGN.md",
];
const files = walk(".").sort();
if (!files.includes("docs/FILE_TREE.md")) files.push("docs/FILE_TREE.md");
files.sort();
const tree =
  "# Full file tree\n\nGenerated by `pnpm exec tsx scripts/sourcebook.ts`; excludes installed dependencies, secrets, local test data and build artifacts.\n\n```text\nAges-of-Ash/\n" +
  files.map((path) => "  " + path).join("\n") +
  "\n```\n";
writeFileSync("docs/FILE_TREE.md", tree);
const ordered = [...priority, ...files.filter((p) => !priority.includes(p))];
let out = "";
for (const path of ordered) {
  const binary = /\.(png|webm)$/i.test(path);
  const content = readFileSync(path).toString(binary ? "base64" : "utf8");
  out += `# ${path}\n\n${binary ? "Binary file: complete base64 encoding; decode to restore.\n\n" : ""}\`\`\`\`${path}\n${content}${content.endsWith("\n") ? "" : "\n"}\`\`\`\`\n\n`;
  if (path === "docs/GAME_DESIGN.md") out += tree + "\n";
}
writeFileSync("SOURCEBOOK.md", out);
console.log(
  `Wrote ${ordered.length} complete files to SOURCEBOOK.md (${Buffer.byteLength(out)} bytes).`,
);
